export const riscs = [
        {
            GrupoDeFatorDeRisco: "teste",
            FatorDeRisco: 1,
            gestor: "teste",
            metrica: "teste",
            ValorDaMetrica: "teste",
            limite: "teste",
            ConsumoDoLimite: "teste",
            ValorDaSimulacao: "teste",
            ConsumoDaSimulacao: "teste",
        },
        {
            GrupoDeFatorDeRisco: "teste",
            FatorDeRisco: 1,
            gestor: "teste",
            metrica: "teste",
            ValorDaMetrica: "teste",
            limite: "teste",
            ConsumoDoLimite: "teste",
            ValorDaSimulacao: "teste",
            ConsumoDaSimulacao: "teste",
        },
        {
            GrupoDeFatorDeRisco: "teste",
            FatorDeRisco: 1,
            gestor: "teste",
            metrica: "teste",
            ValorDaMetrica: "teste",
            limite: "teste",
            ConsumoDoLimite: "teste",
            ValorDaSimulacao: "teste",
            ConsumoDaSimulacao: "teste",
        },
        {
            GrupoDeFatorDeRisco: "teste",
            FatorDeRisco: 1,
            gestor: "teste",
            metrica: "teste",
            ValorDaMetrica: "teste",
            limite: "teste",
            ConsumoDoLimite: "teste",
            ValorDaSimulacao: "teste",
            ConsumoDaSimulacao: "teste",
        },
        {
            GrupoDeFatorDeRisco: "teste",
            FatorDeRisco: 1,
            gestor: "teste",
            metrica: "teste",
            ValorDaMetrica: "teste",
            limite: "teste",
            ConsumoDoLimite: "teste",
            ValorDaSimulacao: "teste",
            ConsumoDaSimulacao: "teste",
        },
        {
            GrupoDeFatorDeRisco: "teste1",
            FatorDeRisco: 2,
            gestor: "teste1",
            metrica: "teste1",
            ValorDaMetrica: "teste1",
            limite: "teste1",
            ConsumoDoLimite: "teste1",
            ValorDaSimulacao: "teste1",
            ConsumoDaSimulacao: "teste1",
        },
        {
            GrupoDeFatorDeRisco: "teste",
            FatorDeRisco: 1,
            gestor: "teste",
            metrica: "teste",
            ValorDaMetrica: "teste",
            limite: "teste",
            ConsumoDoLimite: "teste",
            ValorDaSimulacao: "teste",
            ConsumoDaSimulacao: "teste",
        },
]