export const Users = [
        {
            id   : 1,
            racf : "Hendrix", 
            tipo : 1, 
            active: false, 
            mapa : "Map 2",
        },
        {
            id   : 2,
            racf : "Axl", 
            tipo : 2, 
            active: true, 
            mapa : "Map 2",
        },
        {
            id   : 3,
            racf : "Slash", 
            tipo : 1, 
            active: true, 
            mapa : "Map 3",
        },
        {
            id   : 4,
            racf : "Duff", 
            tipo : 1, 
            active: true, 
            mapa : "Map 5",
        },
        {
            id   : 5,
            racf : "Osbourne", 
            tipo : 1, 
            active: true, 
            mapa : "Map 5",
        },
        {
            id   : 6,
            racf : "Hetfield", 
            tipo : 2, 
            active: true, 
            mapa : "Map 4",
        },
        {
            id   : 7,
            racf : "Veder",
            tipo : 1, 
            active: true, 
            mapa : "Map 3",
        },
        {
            id   : 8,
            racf : "Kurt",
            tipo : 1, 
            active: false, 
            mapa : "Map 3",
        },
        {
            id   : 9,
            racf : "Mustaine",
            tipo : 1, 
            active: true, 
            mapa : "Map 3",
        },
        {
            id   : 10,
            racf : "Coverdale",
            tipo : 2, 
            active: true, 
            mapa : "Map 3",
        },
        {
            id   : 11,
            racf : "Gillan",
            tipo : 2, 
            active: true, 
            mapa : "Map 3",
        },
        {
            id   : 12,
            racf : "Joplin",
            tipo : 1, 
            active: false, 
            mapa : "Map 3",
        },
        {
            id   : 13,
            racf : "Morrison",
            tipo : 1, 
            active: false, 
            mapa : "Map 3",
        },
]